### ISSUE TITLE
The authentication header received from the server was 'Basic realm="AXIS"

### ISSUE THREAD

**Issue by giacatluong** [Travelport/travelport-uapi-tutorial-c-sharp#129]
I was trying the example download from here.. it worked for few calls and in the middle of the example, I got this message.  So  I tried the same credit on demo website and I received the same message.  It does look like the account is locked.. Please unlock it asap.   I think it will happen too often.. is there anyway to keep this unlock ? It's kind of hard trying to figure the capabilities of the service within the trial of 30 days.

Your Credentials: Universal API Web Services
--
Universal API User ID:  Universal API/uAPI-835714743

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P105338

Thank you.

**Comment by vivekjyotipramanik** [comment]
Hi giacatluong,

We have unlocked the credentials. 

The credentials gets unlocked due to invalid password usage. The same TargetBranch and username might have been used by some other trial user and if the trial user tries again with the old password, it gets locked. We do not have any control over that.

If the trial credentials expires before you can evaluate, you can always request for a new set of credentials. Thanks.

**Comment by giacatluong** [comment]
Thank you
