### ISSUE TITLE
Which schema version have to used ?

### ISSUE THREAD

**Issue by yatinmistry** [Travelport/travelport-uapi-tutorial-c-sharp#24]
Hello,

I am currently using version v33_0. Which version  i have to used ? What will be issue migrating from 33 to latest version ? How can we migrate to new schema version in future resales? What issue we have to face?

Thanks,

Yatin Mistry

**Comment by vivekjyotipramanik** [comment]
Hi Yatin,

The current released schema version is version v37_0. 
The new schema version details and functionality upgrades can be found in the below link.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Release_Notes/Release_Notes__16_2.htm%3FTocPath%3DRelease%2520Notes%7C_____3

Generally each schema update comes with several bug fixes and several new upgrades.
We generally retire schema after 3 years from its release.

https://support.travelport.com/webhelp/uapi/uAPI.htm#SchemaRetirement.htm%3FTocPath%3DRelease%2520Notes%7C_____2


If some functionality is removed, it will be stated in the schema release notes.
Generally the recent schema's are backward compatible so it is very unlikely to issues due to migration.

Most of the times the changes in codes are based on new functionality improvements.
Sometimes there are no changes required for migration and sometimes there are few changes required in migration to support new functionality.

It is very tough to quantify the changes required to migrate and it completely based on how you have created your application and how much changes are there in the new release.

Please let me know if that clarify your questions.
Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by yatinmistry** [comment]
Hi Vivekjyoti,

Thanks for the info. i have now migrated from v33 to v35 and its' working fine. 

Thanks,
Yatin Mistry
